name: Deploy
on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          node-version: "20"

      # Set up Deno
      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      # Install Tailwind and dependencies
      - name: Install Tailwind
        run: |
          npm init -y
          npm install -D tailwindcss
          npx tailwindcss init

      # Generate Tailwind CSS
      - name: Build Tailwind CSS
        run: |
          npx tailwindcss -i ./src/input.css -o ./static/styles.css

      # Optional: Run tests
      - name: Run tests
        run: deno test

      # Deploy to Deno Deploy
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: encikpulasan-semut # Replace with your Deno Deploy project name
          entrypoint: main.ts # Your main server file
          root: . # Project root directory
